name: PR Agent for Pull Requests

on:
  workflow_call:
    secrets:
      APIKEY:
        required: true
      TOKEN:
        required: true

jobs:
  Pr_agent_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
      pull-requests: write
      contents: write

    name: Run PR Agent
    if: ${{ github.event.sender.type != 'Bot'}}
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.APIKEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          github_action.auto_describe: true
          github_action.auto_review: true
          github_action.auto_improve: false
          github_action.enable_output: false
          github_action.model: 'gpt-3.5-turbo-16k'
          github_action.model_turbo: 'gpt-3.5-turbo-16k'
          PR_REVIEWER.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions.'
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions. Titles should have prefix of commitlint pattern such as `feat:`, `chore:`, `test:`, `fix:`, `ci:`, `docs:` etc'
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: 'Please use Japanese.'
