name: Build Next.js

on:
  workflow_call:
    secrets:
      APIKEY:
        required: true
      TOKEN:
        required: true

jobs:
  build_next_js:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      # githubのコンソールから入力したリリース名を環境変数へ保存
      RELEASE_BRANCH_NAME: release/${{ github.event.inputs.version }}
      # PR_URL: ${{ github.event.pull_request.html_url }}
      # GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.4
        with:
          node-version: "${{ secrets.TOKEN }}"

      - name: Set release branch name
        run: echo "RELEASE_BRANCH_NAME=release/$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Create and push release branch
        run: |
          git checkout -b ${{ env.RELEASE_BRANCH_NAME }}
          git push origin ${{ env.RELEASE_BRANCH_NAME }}

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "${{ vars.GIT_ACTIONS_NODE_VER }}"

      - uses: actions/cache@v4.0.2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Check if package-lock.json exists
        run: echo "$([[ -e 'package-lock.json' ]] && echo 'yes' || echo 'no')"
        id: check_package_lock

      - name: Dependency Installation (If there is no cache)
        if: steps.restore_node_modules.outputs.cache-hit != 'true' || steps.check_package_lock.outputs.result == 'no'
        run: npm install

      - name: Build Next.js App
        run: npm run build
        env:
          MICROCMS_SERVICE_DOMAIN: ${{ vars.MICROCMS_SERVICE_DOMAIN }}
          MICROCMS_API_KEY: ${{ secrets.APIKEY }}

      # releasブランチ -> mainブランチへのPull Requestを作成
      - name: Create Pull Request dev2stage
        id: create-pull-request
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          PULL_REQUEST_URI=$(gh pr create -B stage -t ${{ env.RELEASE_BRANCH_NAME }} -b "")
          echo "::set-output name=PULL_REQUEST_URI::$PULL_REQUEST_URI"

      - name: Merge Pull Request dev2stage
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh pr merge ${{steps.create-pull-request.outputs.PULL_REQUEST_URI}} --merge
