name: Build Next.js

on:
  workflow_call:
    secrets:
      APIKEY:
        required: true
      TOKEN:
        required: true

jobs:
  build_next_js:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Create production branch
        run: |
          git checkout -b production
          git push origin production

      - name: Check out repository
        uses: actions/checkout@v4.1.4

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "${{ vars.GIT_ACTIONS_NODE_VER }}"

      - uses: actions/cache@v4.0.2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Check if package-lock.json exists
        run: echo "$([[ -e 'package-lock.json' ]] && echo 'yes' || echo 'no')"
        id: check_package_lock

      - name: Dependency Installation (If there is no cache)
        if: steps.restore_node_modules.outputs.cache-hit != 'true' || steps.check_package_lock.outputs.result == 'no'
        run: npm install

      - name: Build Next.js App
        run: npm run build
        env:
          MICROCMS_SERVICE_DOMAIN: ${{ vars.MICROCMS_SERVICE_DOMAIN }}
          MICROCMS_API_KEY: ${{ secrets.APIKEY }}

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Build Next.js"

      - name: Push changes to production branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: production

      - name: Merge production into main
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin production --ff-only
          git push origin HEAD:refs/heads/main
