name: PR Agent for Pull Requests

on:
  workflow_call:
    secrets:
      issue_number:
        required: true
      owner:
        required: true
      repo:
        required: true
      body:
        required: true

jobs:
  Pr_agent_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
      pull-requests: write
      contents: write

    name: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.6

      - name: PR Agent action step
        run: |
          echo "test"
