name: Delete Branch After Merge

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  delete-branch:
    if: startsWith(github.head_ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin --delete ${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          # if [[ "$BRANCH_NAME" == release* ]]; then
          #   git push origin --delete $BRANCH_NAME
          # fi
