name: Get Diff

on:
  workflow_dispatch:

jobs:
  get_diff:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Get merge commit
        id: merge_commit
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/merge
          echo "::set-output name=sha::$(git rev-parse FETCH_HEAD)"

      - name: Get diff
        id: diff
        run: |
          merge_sha="${{ steps.merge_commit.outputs.sha }}"
          base_sha=$(git merge-base $merge_sha^1 $merge_sha)
          git diff --name-only $base_sha $merge_sha > diff.txt

          # Output the diff
          cat diff.txt
