name: Markup Lint & Rewrite

on:
  workflow_call:

jobs:
  Markup_Linter:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    name: MarkUp Linter
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "${{ vars.GIT_ACTIONS_NODE_VER }}"
          cache: npm

      - name: Cache node (if not already cached)
        id: cache_dependency
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Lint and rewrite markup
        run: npm run lint:markuplint

  Prettier:
    needs: Markup_Linter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    name: Prettier
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "${{ vars.GIT_ACTIONS_NODE_VER }}"
          cache: npm

      - name: Cache node (if not already cached)
        id: cache_dependency
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Lint and rewrite markup
        run: npm run lint:prettier

      - name: Auto-commit changes (optional)
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: Automatically format code with Prettier
