name: Markup Lint & Rewrite

on:
  workflow_call:

jobs:
  Markup_Linter:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    name: MarkUp Linter
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.head_ref }}

      - name: Lint and rewrite markup
        run: npm run lint:markuplint

  Prettier:
    needs: Markup_Linter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    name: Prettier
    steps:
      - name: Lint and rewrite markup
        run: npm run lint:prettier

      - name: Auto-commit changes (optional)
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: Automatically format code with Prettier
