name: npm cache

on:
  workflow_call:
    inputs:
      node_version:
        required: true

permissions:
  contents: write
  pull-requests: read

jobs:
  cache_npm:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version:  ${{ inputs.node_version }}
          cache: npm

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependency
        if: ${{ steps.cache_dependency.outputs.cache-hit != 'true' }}
        run: npm ci --no-audit --progress=false --silent
