on:
  workflow_call:

jobs:
  cache_npm:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4.x
        with:
          node-version: 20.x
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

#    - name: Cache next build
#      uses: actions/cache@v4.x
#      with:
#        path: ./.next/cache
#        key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
