name: Build_Setup

on:
  workflow_call:

jobs:
  cache_npm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {}

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "${{ vars.GIT_ACTIONS_NODE_VER }}"
          cache: npm



      - name: Check if package-lock.json exists
        run: |
          file_present=$(echo "file_present='$(ls -1 package-lock.json 2>/dev/null | wc -l)'" | bash)
          echo "File Present: ${{ file_present }}"
          exit ${{ file_present }}

      - name: Cache node (if package-lock.json exists)
        if: ${{ steps.check_package_lock_exists.outputs.file_present == '1' }}
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies (if cache miss or no package-lock.json)
        if: ${{ steps.cache_npm.outputs.cache-hit != 'true' || steps.check_package_lock_exists.outputs.file_present != '1' }}
        run: npm ci --no-audit --progress=false --silent

      - name: Install dependencies
        if: ${{ steps.cache_npm.outputs.cache-hit != 'false' || steps.check_package_lock_exists.outputs.file_present != '0' }}
        run: npm install



      # - name: Cache node (if not already cached)
      #   id: cache_dependency
      #   uses: actions/cache@v4.0.2
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      # - name: Install dependencies (if cache miss)
      #   if: ${{ steps.cache_dependency.outputs.cache-hit != 'true' }}
      #   run: |
      #     if [ ! -f "package-lock.json" ]; then
      #       npm install --no-audit --progress=false --silent
      #     else
      #       npm ci --no-audit --progress=false --silent
      #     fi
