name: UPLOAD

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

jobs:
  UPLOAD:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.head_ref }}

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4.0.2
      #   with:
      #     node-version: "${{ vars.GIT_ACTIONS_NODE_VER }}"
      #     cache: npm

      # - name: Restore node_modules
      #   uses: actions/cache@v4.0.2
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      #     restore-keys: ${{ runner.os }}-node-

      # - name: Dependency Installation (If there is no cache)
      #   if: steps.restore_node_modules.outputs.cache-hit != 'true'
      #   run: npm ci --no-audit --progress=false --silent




        # - name: Build Next.js app
        #   if: github.event_name == 'repository_dispatch'  # repository_dispatch イベントの場合のみ実行
        #   run: npm run build

        # - name: Deploy via FTP
        #   if: github.ref == 'refs/heads/main'  # mainブランチにマージされた場合のみ実行
        #   uses: SamKirkland/FTP-Deploy-Action@4.2.0
        #   with:
        #     protocol: ftp
        #     server: ${{ vars.HOST }}       # FTPのサーバーアドレス
        #     username: ${{ vars.USER_NAME }}   # FTPのユーザー名
        #     password: ${{ secrets.FTP_PASSWORD }}   # FTPのパスワード
        #     local-dir: ${{ vars.LOCAL_PATH }}      # アップロードしたいファイルのパス、この場合srcディレクトリ内をアップロード対象としている
        #     server-dir: ${{ vars.REMOTE_PATH }}     # アップロード先のリモートパス




        - name: Deploy via SFTP
          uses: wangyucode/sftp-upload-action@v2.0.2
          with:
            host: ${{ vars.SFTP_HOST }}
            username: ${{ vars.SFTP_USER_NAME }}
            password: ${{ secrets.SFTP_PASSWORD }}
            localDir: ${{ vars.LOCAL_PATH }}
            remoteDir: /faloom.jp/pc/test/
            port:  ${{ vars.SFTP_PORT }}
