name: Pull Request init

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  PR_AGENT:
    uses: ./.github/workflows/_pr_agent.yml
    secrets:
      APIKEY: '${{ secrets.OPENAI_KEY }}'
      TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  COMMENT_OPENING_ANNOUNCE:
    needs: PR_AGENT
    uses: ./.github/workflows/_init_comment.yml
