name: CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  BUILD_SETUP:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && startsWith(github.head_ref, 'develop')
    uses: ./.github/workflows/_npm.yml

  AUTO_MERGE:
    needs: BUILD_SETUP
    uses: ./.github/workflows/_auto_merge_deploycd.yml
    secrets:
      APIKEY: '${{ secrets.MICROCMS_API_KEY }}'
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PTOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  CREATE_TAG:
    needs: AUTO_MERGE
    uses: ./.github/workflows/_create_relese_note.yml
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
