name: CI

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
    paths:
      - '**'
      - '!public/**'

jobs:
  Markup_Linter:
    if: github.event.sender.type != 'Bot' && contains(github.head_ref, 'develop')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - run: echo 'skip'

  Markup_Linter_no_need:
    name: Markup Linter(no need)
    if: github.event.sender.type == 'Bot' || contains(github.head_ref, 'release')
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: read

    steps:
      - run: echo 'skip'

  Lighthouse:
    name: Lighthouse-CI
    if: github.event.sender.type != 'Bot' && contains(github.head_ref, 'develop')
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - run: echo 'skip'

  Lighthouse_no_need:
    name: Lighthouse-CI(no need)
    if: github.event.sender.type == 'Bot' || contains(github.head_ref, 'release')
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: read

    steps:
      - run: echo 'skip'
