name: Deploy to Develop Branch & Create release tag and release note.

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  PR_AGENT:
    uses: ./.github/workflows/upload.yml
    with:
      node_version: "${{ vars.GIT_ACTIONS_NODE_VER }}"
