name: Deploy to Develop Branch

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  workflow_call_npm:
    uses: ./.github/workflows/_npm.yml
    with:
      node_version: "${{ vars.GIT_ACTIONS_NODE_VER }}"
  upload:
    needs:
      - workflow_call_npm

    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && startsWith(github.head_ref, 'develop')

    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "${{ vars.GIT_ACTIONS_NODE_VER }}"

      - name: Restore node_modules
        uses: actions/cache@v4.0.2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
