name: Handle PR from Develop Branch

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  error_handling:
    runs-on: ubuntu-latest

    timeout-minutes: 3

    steps:
        run: echo "${{ vars.GIT_ACTIONS_NODE_VER }}"
        run: echo "`${{ vars.GIT_ACTIONS_NODE_VER }}`"
      - name: Check if PR is from develop branch
        if: github.event_name == 'pull_request' && !startsWith(github.head_ref, 'develop')
        run: exit 1
