name: Handle PR from Develop Branch

on:
  pull_request:
    branches:
      - main

jobs:
  error_handling:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from develop branch
        if: github.event_name == 'pull_request' && !startsWith(github.head_ref, 'develop')
        run: exit 1
