name: HOOK

on:
  workflow_dispatch:

jobs:
  BUILD:
    uses: ./.github/workflows/_build_nextjs.yml
    secrets:
      APIKEY: '${{ secrets.MICROCMS_API_KEY }}'
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
