name: HOOK

on:
  repository_dispatch:
    types: [update-posts]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check webhook payload
        id: check_payload
        run: |
          echo "id=${{ github.event.client_payload.id }}" >> $GITHUB_OUTPUT

      - name: Set up cURL
        uses: wei/curl@v1

      - name: Get Data from MicroCMS
        env:
          article_id: ${{ steps.check_payload.outputs.id }}
          domain: ${{ vars.MICROCMS_SERVICE_DOMAIN }}
          api_key: ${{ secrets.MICROCMS_API_KEY }}
        run: |
          DATA=$(curl -X GET "https://${{ env.domain }}.microcms.io/api/v1/news/${{ env.article_id }}" -H "X-MICROCMS-API-KEY: ${{ env.api_key }}")
          echo "$DATA" > data.json
          echo "data=$(cat data.json | jq -c '.')" >> $GITHUB_ENV

      - name: Confirm Data
        env:
          REPOSITORY: ${{ github.event.repository.name }}
          DATA: ${{ env.data }}
        run: |
          echo "$REPOSITORY"
          echo "Data received from MicroCMS:"
          echo "$DATA"
          CATEGORY=$(echo "$DATA" | jq -r '.category[0]')
          echo "Category: $CATEGORY"
          if [[ "$CATEGORY" == "$REPOSITORY" ]]; then
            echo "Category match: true"
            echo "exists_brand=1" >> $GITHUB_ENV
          else
            echo "Category match: false"
            echo "exists_brand=0" >> $GITHUB_ENV
          fi

      - name: Build Next.js App
        run: |


  # curl "https://70iz3quiza.microcms.io/api/v1/news/em2pj_ygl6n" -H "X-MICROCMS-API-KEY: 3ULBgPQ3H9xwDnj8GZ3ePlTccQn66gWPNY70"


  # AUTO_MERGE:
  #   needs: test
  #   uses: ./.github/workflows/_auto_merge_deploycd.yml
  #   secrets:
  #     APIKEY: '${{ secrets.MICROCMS_API_KEY }}'
  #     TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     PTOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


#   {
#   service: 'webhook-test',
#   api: 'news',
#   id: 'x2xkcwog9521',
#   type: 'edit',
#   contents: {
#     old: {
#       id: 'x2xkcwog9521',
#       status: ['DRAFT'],
#       draftKey: 'Vyf_XTclTY',
#       publishValue: null,
#       draftValue: {
#         id: 'x2xkcwog9521',
#         createdAt: '2021-06-02T05:56:24.513Z',
#         updatedAt: '2021-06-02T06:05:09.601Z',
#         publishedAt: '2021-06-02T06:05:09.601Z',
#         revisedAt: '2021-06-02T06:05:09.601Z',
#         title: 'タイトルです',
#       },
#     },
#     new: {
#       id: 'x2xkcwog9521',
#       status: ['PUBLISH'],
#       draftKey: null,
#       publishValue: {
#         id: 'x2xkcwog9521',
#         createdAt: '2021-06-02T05:56:24.513Z',
#         updatedAt: '2021-06-02T06:05:09.601Z',
#         publishedAt: '2021-06-02T06:05:09.601Z',
#         revisedAt: '2021-06-02T06:05:09.601Z',
#         title: 'タイトルです',
#       },
#       draftValue: null,
#     },
#   },
# }
