name: HOOK

on:
  repository_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event is '${{ github.event.action }}'"
          echo "Message is '${{ github.event.client_payload.message }}'"

  # AUTO_MERGE:
  #   needs: test
  #   uses: ./.github/workflows/_auto_merge_deploycd.yml
  #   secrets:
  #     APIKEY: '${{ secrets.MICROCMS_API_KEY }}'
  #     TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     PTOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
