name: Deploy website on push
on:
  push:
    branches: 
    - main
  # repository_dispatch:
  #   types:
  #     - posts_update

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy
      uses: appeboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.SSH_REMOTE_PATH }}
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'cd ${{ secrets.SSH_REMOTE_PATH }} && git pull'
