name: Deploy website on push
on:
  push:
    branches: [main]
  repository_dispatch:
    types: [posts_update]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Check out code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'  # 使用したいNode.jsのバージョンを指定します

        - name: Build Next.js app
          if: github.event_name == 'repository_dispatch'  # repository_dispatch イベントの場合のみ実行
          run: npm run build

        - name: Deploy via FTP
          if: github.ref == 'refs/heads/main'  # mainブランチにマージされた場合のみ実行
          uses: SamKirkland/FTP-Deploy-Action@4.2.0
          with:
            protocol: ftp
            server: ${{ variables.HOST }}       # FTPのサーバーアドレス
            username: ${{ variables.USER_NAME }}   # FTPのユーザー名
            password: ${{ secrets.FTP_PASSWORD }}   # FTPのパスワード
            local-dir: ${{ variables.LOCAL_PATH }}      # アップロードしたいファイルのパス、この場合srcディレクトリ内をアップロード対象としている
            server-dir: ${{ variables.REMOTE_PATH }}     # アップロード先のリモートパス

        - name: Commit and push build changes
          if: github.event_name == 'repository_dispatch'  # repository_dispatch イベントの場合のみ実行
          run: |
            git config --local user.email "sysadmin@pia-corp.jp"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Build Next.js app"
            git push origin main
