name: deploy
on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - posts_update
  pull_request:
    branches:
      - main
    types:
      - closed


jobs:
  workflow_call_npm:
    uses: ./.github/workflows/_npm.yml

  upload:
    needs:
      - workflow_call_npm

    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-


          # uses: actions/cache@v4
          # with:
          #   path: ~/.npm
          #   key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          #   restore-keys: ${{ runner.os }}-npm-

        # - name: Install node modules
        #   if: steps.cache.npm.cache-hit == 'false'
        #   run: npm install

        # - name: CI node modules
        #   if: steps.cache.npm.cache-hit == 'true'
        #   run: npm ci

        # - name: Build Next.js app
        #   if: github.event_name == 'repository_dispatch'  # repository_dispatch イベントの場合のみ実行
        #   run: npm run build

        # - name: Deploy via FTP
        #   if: github.ref == 'refs/heads/main'  # mainブランチにマージされた場合のみ実行
        #   uses: SamKirkland/FTP-Deploy-Action@4.2.0
        #   with:
        #     protocol: ftp
        #     server: ${{ vars.HOST }}       # FTPのサーバーアドレス
        #     username: ${{ vars.USER_NAME }}   # FTPのユーザー名
        #     password: ${{ secrets.FTP_PASSWORD }}   # FTPのパスワード
        #     local-dir: ${{ vars.LOCAL_PATH }}      # アップロードしたいファイルのパス、この場合srcディレクトリ内をアップロード対象としている
        #     server-dir: ${{ vars.REMOTE_PATH }}     # アップロード先のリモートパス




        # - name: Deploy via SFTP
        #   uses: wangyucode/sftp-upload-action@v2.0.2
        #   with:
        #     host: ${{ vars.SFTP_HOST }}
        #     username: ${{ vars.SFTP_USER_NAME }}
        #     password: ${{ secrets.SFTP_PASSWORD }}
        #     localDir: ${{ vars.LOCAL_PATH }}
        #     remoteDir: /faloom.jp/pc/test/
        #     port:  ${{ vars.SFTP_PORT }}

        # - name: Commit and push build changes
        #   if: github.event_name == 'repository_dispatch'  # repository_dispatch イベントの場合のみ実行
        #   run: |
        #     git config --local user.email "sysadmin@pia-corp.jp"
        #     git config --local user.name "GitHub Action"
        #     git add .
        #     git commit -m "Build Next.js app"
        #     git push origin main
