name: PR Agent for Pull Requests

on:
  push:
    branches:
      - main

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
      contents: write

    timeout-minutes: 5

    name: Run PR Agent
    if: ${{ github.event.sender.type != 'Bot'}}
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action.auto_describe: true
          github_action.auto_review:   true
          github_action.auto_improve:  false
          github_action.enable_output:  true
          github_action.push_changelog_changes: true
          PR_REVIEWER.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions.'
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions. Titles should have prefix of commitlint pattern such as `feat:`, `chore:`, `test:`, `fix:`, `ci:`, `docs:` etc'
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: 'Please use Japanese.'
