name: Pretter

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: "20"

jobs:
  # action:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Action
  #     - uses: pia-corp/test@main
  #       with:
  #         version: ${{ env.node_version }}
  call_reusable_workflow_on_same_repository:
    uses: ./.github/workflows/_npm.yml

  hogehoge:
    needs:
      - call_reusable_workflow_on_same_repository

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Run Lint
        id: prettier
        run: npm run lint:prettier

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatically format code with Prettier
