name: Markup Lint & Rewrite

on:
  workflow_call:

jobs:
  call_workflow:
    uses: ./.github/workflows/_npm.yml
    with:
      node_version: "${{ vars.GIT_ACTIONS_NODE_VER }}"

  lint-and-rewrite:
    needs:
      - call_workflow

    runs-on: ubuntu-latest
    timeout-minutes: 5

    name: MarkUp Linter
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "${{ vars.GIT_ACTIONS_NODE_VER }}"

      - name: Restore node_modules
        uses: actions/cache@v4.0.2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Dependency Installation (If there is no cache)
        if: steps.restore_node_modules.outputs.cache-hit != 'true'
        run: npm ci --no-audit --progress=false --silent

      - name: Lint and rewrite markup
        run: npm run lint

      - name: Auto-commit changes (optional)
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: Automatically format code with Prettier
