name: Pretter

on:
  pull_request:
    branches:
      - main

env:
  FILE_PATTERN: "{out,__tests__}/**/*.{html,css,js,jsx}"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Cache npm directory
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install node modules
        # if: steps.cache.npm.cache-hit == 'false'
        run: npm install

      - name: Run Lint
        id: prettier
        run: npm run lint

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatically format code with Prettier
