name: Markup lint and rewrite

on:
  pull_request:
    branches:
      - main

jobs:
  call_workflow:
    uses: ./.github/workflows/_npm.yml
    with:
      node_version: `${{ vars.GIT_ACTIONS_NODE_VER }}`

  linter:
    needs:
      - call_workflow

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: `${{ vars.GIT_ACTIONS_NODE_VER }}`

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Run Lint
        run: npm run lint

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatically format code with Prettier
