name: Push

on:
  pull_request:
    branches:
      - main

jobs:
  steps:
    - name: NPM_CACHE
      uses: ./.github/workflows/_npm.yml
      with:
        node_version: "${{ vars.GIT_ACTIONS_NODE_VER }}"

    - name: LINTER
      needs: NPM_CACHE
      uses: ./.github/workflows/prettier.yml

    - name: LIGHTHOUSE
      uses: ./.github/workflows/lighthouse.yml
