name: Push

on:
  pull_request:
    branches:
      - main
    types: [edited, synchronize]

jobs:
  BUILD_SETUP:
    if: ${{ github.event.sender.type != 'Bot' }} && github.event_name == 'pull_request' && (!startsWith(github.head_ref, 'develop') || !startsWith(github.head_ref, 'hotfix'))
    uses: ./.github/workflows/_npm.yml

  LINTER:
    needs: BUILD_SETUP
    uses: ./.github/workflows/_linter.yml

  CORE_WEB_VITALS:
    needs: LINTER
    uses: ./.github/workflows/_lighthouse.yml
    secrets:
      TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
