name: Push

on:
  pull_request:
    branches:
      - main
    types: [edited, synchronize]

jobs:
  SET_INIT:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: build
        if: ${{ github.event.sender.type != 'Bot' }} && (!startsWith(github.head_ref, 'develop') || !startsWith(github.head_ref, 'hotfix'))
        uses: ./.github/workflows/_npm.yml

      - name: linter
        needs: build
        uses: ./.github/workflows/_linter.yml
        with:
          head_ref: ${{ github.head_ref }}

      - name: core_web_vitals
        needs: linter
        uses: ./.github/workflows/_lighthouse.yml
        secrets:
          TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
