name: Push

on:
  pull_request:
    branches:
      - main
    types: [edited, synchronize]

jobs:
  SET_INIT:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.head_ref }}
        if: ${{ github.event.sender.type != 'Bot' }} && (!startsWith(github.head_ref, 'develop') || !startsWith(github.head_ref, 'hotfix'))

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "${{ vars.GIT_ACTIONS_NODE_VER }}"
          cache: npm

      - name: Cache node (if not already cached)
        id: cache_dependency
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies (if cache miss)
        if: ${{ steps.cache_dependency.outputs.cache-hit != 'true' }}
        run: npm ci --no-audit --progress=false --silent

      - name: linter
        uses: ./.github/workflows/_linter.yml

      - name: core_web_vitals
        uses: ./.github/workflows/_lighthouse.yml
        with:
          TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
