name: Push

on:
  pull_request:
    branches:
      - main
    types: [edited, synchronize]

jobs:
  Build_Setup:
    uses: ./.github/workflows/_npm.yml

  LINTER:
    needs: Build_Setup
    uses: ./.github/workflows/_linter.yml

  LIGHTHOUSE:
    needs: LINTER
    uses: ./.github/workflows/_lighthouse.yml
    secrets:
      TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
