name: Push

on:
  pull_request:
    branches:
      - main
    types: [edited, synchronize]

jobs:
  LINTER:
    uses: ./.github/workflows/prettier.yml

  LIGHTHOUSE:
    needs: LINTER
    uses: ./.github/workflows/lighthouse.yml
