name: Quick CI

on:
  push:
    branches:
      - main
      - develop
      - feature

jobs:
  BUILD_SETUP:
    uses: ./.github/workflows/_npm.yml

  LINTER:
    needs: BUILD_SETUP
    uses: ./.github/workflows/_linter.yml

  CORE_WEB_VITALS:
    needs: BUILD_SETUP
    uses: ./.github/workflows/_lighthouse.yml
    secrets:
      TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
