name: Quick CI

on:
  push:

jobs:
  BUILD_SETUP:
    if: ${{ github.event.sender.type != 'Bot' }}
    uses: ./.github/workflows/_npm.yml

  LINTER:
    needs: BUILD_SETUP
    uses: ./.github/workflows/_linter.yml

  CORE_WEB_VITALS:
    needs: BUILD_SETUP
    uses: ./.github/workflows/_lighthouse.yml
