name: Reservation

on:
  workflow_dispatch:
    inputs:
      month:
        type: choice
        required: true
        description: 月
        options:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
      day:
        type: choice
        required: true
        description: 日
        options:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
          - 27
          - 28
          - 29
          - 30
          - 31
      hour:
        type: choice
        required: true
        description: 時間
        options:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
      minutes:
        type: choice
        required: true
        description: 分
        options:
          - 00
          - 10
          - 20
          - 30
          - 40
          - 50

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Register Cron job
        env:
          month: ${{ github.event.inputs.month }}
          day: ${{ github.event.inputs.day }}
          hour: ${{ github.event.inputs.hour }}
          minutes: ${{ github.event.inputs.minutes }}
        run: |
          # Cron jobのURLと認証トークンを設定
          CRON_JOB_URL="https://api.cron-job.org"
          AUTH_TOKEN="GOmptxhN7sYnzVZiV0XMFJWVfRrjy2avJ0xtauPuMcs="

          curl -X PATCH \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer GOmptxhN7sYnzVZiV0XMFJWVfRrjy2avJ0xtauPuMcs=' \
          -d '{"job":"schedule":{"hours":${{env.hour}},"mdays":${{env.day}},"minutes":${{env.minutes}},"months":${{env.month}}}}' \
          https://api.cron-job.org/jobs/5132071

# curl -X PUT \
# -H 'Content-Type: application/json' \
# -H 'Authorization: Bearer GOmptxhN7sYnzVZiV0XMFJWVfRrjy2avJ0xtauPuMcs=' \
# -d '{"job":{"url":"https://example.com","enabled":"true","saveResponses":true,"schedule":{"timezone":"Europe/Berlin","expiresAt":0,"hours":[-1],"mdays":[-1],"minutes":[-1],"months":[-1],"wdays":[-1]}}}' \
# https://api.cron-job.org/jobs


# # cron-job APIにリクエストを送信
# curl -X POST -H "Authorization: Bearer $AUTH_TOKEN" \
#       -H "Content-Type: application/json" \
#       -d '{
#         "name": "$CRON_JOB_NAME",
#         "schedule": "$CRON_SCHEDULE",
#         "action": "$CRON_JOB_ACTION"
#       }' \
#       "$CRON_JOB_URL"

# curl -X PATCH \
# -H 'Content-Type: application/json' \
# -H 'Authorization: Bearer GOmptxhN7sYnzVZiV0XMFJWVfRrjy2avJ0xtauPuMcs=' \
# -d '{"job":{"enabled":true}}' \
# https://api.cron-job.org/jobs/5132071
