name: Reservation

on:
  workflow_dispatch:
    inputs:
      年:
        type: choice
        required: true
        description: 年
        options:
          - 2024
          - 2025
          - 2026
          - 2027
          - 2028
          - 2029
          - 2030
          - 2031
          - 2032
          - 2033
          - 2034
          - 2035
      月:
        type: choice
        required: true
        description: 月
        options:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
      日:
        type: choice
        required: true
        description: 日
        options:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
          - 27
          - 28
          - 29
          - 30
          - 31
      時間:
        type: choice
        required: true
        description: 時間
        options:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
      分:
        type: choice
        required: true
        description: 分
        options:
          - 00
          - 10
          - 20
          - 30
          - 40
          - 50


jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git configuration
        run: |
          echo "test"

      - name: Register Cron job
        run: |
          # Cron jobのURLと認証トークンを設定
          CRON_JOB_URL="https://api.cron-job.org"
          AUTH_TOKEN="GOmptxhN7sYnzVZiV0XMFJWVfRrjy2avJ0xtauPuMcs="

          # Cron jobの情報を設定
          CRON_JOB_NAME="my-cron-job"
          CRON_SCHEDULE="* * * * *"  # 毎分実行
          CRON_JOB_ACTION="echo 'Hello, world!'"

          curl -X PATCH \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer GOmptxhN7sYnzVZiV0XMFJWVfRrjy2avJ0xtauPuMcs=' \
          -d '{"job":{"enabled":true}}' \
          https://api.cron-job.org/jobs/5128562

# curl -X PUT \
# -H 'Content-Type: application/json' \
# -H 'Authorization: Bearer GOmptxhN7sYnzVZiV0XMFJWVfRrjy2avJ0xtauPuMcs=' \
# -d '{"job":{"url":"https://example.com","enabled":"true","saveResponses":true,"schedule":{"timezone":"Europe/Berlin","expiresAt":0,"hours":[-1],"mdays":[-1],"minutes":[-1],"months":[-1],"wdays":[-1]}}}' \
# https://api.cron-job.org/jobs


# # cron-job APIにリクエストを送信
# curl -X POST -H "Authorization: Bearer $AUTH_TOKEN" \
#       -H "Content-Type: application/json" \
#       -d '{
#         "name": "$CRON_JOB_NAME",
#         "schedule": "$CRON_SCHEDULE",
#         "action": "$CRON_JOB_ACTION"
#       }' \
#       "$CRON_JOB_URL"

# curl -X PATCH \
# -H 'Content-Type: application/json' \
# -H 'Authorization: Bearer GOmptxhN7sYnzVZiV0XMFJWVfRrjy2avJ0xtauPuMcs=' \
# -d '{"job":{"enabled":true}}' \
# https://api.cron-job.org/jobs/5132071
