name: Sync Directory Changes to Multiple Repositories

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'

jobs:
  DispatchDirectoryChanges:
    strategy:
      matrix:
        repo: [
          'pia-corp/template',
          'pia-corp/faloom',
          ]
    name: dispatch-directory-changes
    runs-on: ubuntu-latest
    steps:
      - name: repository-dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: directory-changes
