name: Sync Directory Changes to Multiple Repositories

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'

jobs:
  dispatch-directory-changes:
    strategy:
      matrix:
        repo: ['pia-corp/template']
    name: Do dispatch-directory-changes
    # ジョブが実行されるマシンの種類。
    runs-on: ubuntu-latest
    steps:
      # アプリ側リポジトリで `repository_dispatch` を使って通知を受け取るので `peter-evans/repository-dispatch` を使用
      - name: Do repository-dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          # 対象がPrivateなリポジトリのためtokenをセット（内容は後述）
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # 定義しておいた通知対象リポジトリを指定
          repository: ${{ matrix.repo }}
          # イベントタイプを `directory-changes` にしておく
          event-type: directory-changes
