name: Sync Directory Changes to Multiple Repositories

on:
  push:
    paths:
      - '.github/**'

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4.1.6

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changes
        id: changes
        run: |
          # Ensure we have previous commit to compare
          if [ $(git rev-parse --is-shallow-repository) = "true" ]; then
            git fetch --prune --unshallow
          fi

          # Check for changes in the specified directory
          changed_files=$(git diff --name-only HEAD^ HEAD -- .github/)

          # Output the result to be used in the next step
          echo "changed_files=$changed_files" >> $GITHUB_ENV

      - name: Sync files to other repositories
        if: env.changed_files != ''
        env:
          REPO_1: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/pia-corp/template.git
          # Add more repositories as needed
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # 変更されたファイルのリストを取得
          changed_files=$(git diff --name-only HEAD^ HEAD -- .github/)

          # 各ターゲットリポジトリに対して変更を同期
          for repo in $REPO_1; do
            git clone --depth=1 $repo target_repo
            cd target_repo

            # 変更されたファイルをコピー
            for file in $changed_files; do
              rsync -av --relative "../$file" "./"
            done

            # 変更をコミットしてプッシュ
            git add .
            git commit -m "Sync from main repository"
            git push origin main
            cd ..
            rm -rf target_repo
          done
