name: Sync Directory Changes to Multiple Repositories

on:
  workflow_dispatch:

jobs:
  DispatchDirectoryChanges:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repos: ['pia-corp/template']

    steps:
      - name: repository-dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ matrix.repos }}
          event-type: directory-changes
