name: TEST

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      # githubのコンソールから入力したリリース名を環境変数へ保存
      RELEASE_BRANCH_NAME: release/${{ github.event.inputs.version }}
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.head_ref }}

      - name: Generate release tag
      id: release_tag
      run: |
        echo "${{ env.RELEASE_BRANCH_NAME }}"
        echo "${{ env.PR_URL }}"
