name: Bump version2
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Get tag
        id: tag
        run: |
          echo "::set-output name=date::$(date +'%Y%m%d')"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          CUSTOM_TAG: v${{ steps.tag.outputs.date }}-${{ steps.tag.outputs.sha_short }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.bump.outputs.new_tag }}
          tag_name: ${{ steps.bump.outputs.new_tag }}
