name: FILE UPLOAD

on:
  workflow_dispatch:
    # inputs:
    #   sync_type:
    #     type: choice
    #     description: '同期タイプ'
    #     required: true
    #     default: 'SFTP'
    #     options:
    #       - 'SFTP'
    #       - 'FTP'

jobs:
  UPLOAD:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.head_ref }}


      - name: Deploy via SFTP
        uses: wangyucode/sftp-upload-action@v2.0.2
        if: ${{ vars.PROTOCOL }} == 'SFTP'
        with:
          host: ${{ vars.HOST }}
          port:  ${{ vars.PORT }}
          username: ${{ vars.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          privateKey: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          localDir: ${{ vars.LOCAL_PATH }}
          remoteDir: ${{ vars.REMOTE_PATH }}
          # removeExtraFilesOnServer: false
