name: FILE UPLOAD

on:
  workflow_dispatch:
    inputs:
      sync_type:
        type: choice
        description: '同期タイプ'
        required: true
        default: 'delta'
        options:
          - 'delta'
          - 'full'

jobs:
  UPLOAD:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
          # ref: ${{ github.head_ref }}

      - name: "Deploy"
        uses: milanmk/actions-file-deployer@1.14
        with:
          remote-protocol: "sftp"
          # remote-protocol: '${{ vars.PROTOCOL }}'
          remote-port:  '${{ vars.PORT }}'
          remote-host: '${{ vars.HOST }}'
          remote-user: '${{ vars.USER_NAME }}'
          remote-password: '${{ secrets.PASSWORD }}'
          ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          local-path: '${{ vars.LOCAL_PATH }}'
          sync: "full"
          # sync: '${{ inputs.sync_type }}'
          remote-path: '${{ vars.REMOTE_PATH }}'
