name: FILE UPLOAD

on:
  workflow_dispatch:

jobs:
  UPLOAD:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - name: Check if the executor is the repository owner
        if: github.actor != github.repository_owner
        run: |
          echo "Error handling"
          echo "アップロード権限がありません。コードオーナーに依頼してください。
          exit 1

      - uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.head_ref }}

      - name: Error handling
        if: ${{ vars.PROTOCOL  == 'FTP' || vars.PROTOCOL  == 'SFTP' }}
        run: |
          echo "Error handling"
          echo "プロトコルの指定が不正です。protocol = ${{ vars.PROTOCOL }}"
          exit 1

      - name: Deploy via SFTP
        if: ${{ vars.PROTOCOL  == 'SFTP' }}
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ vars.HOST }}
          port:  ${{ vars.PORT }}
          username: ${{ vars.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          privateKey: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          localDir: ${{ vars.LOCAL_PATH }}
          remoteDir: ${{ vars.REMOTE_PATH }}
          # removeExtraFilesOnServer: false

      - name: Deploy via FTP
        if: ${{ vars.PROTOCOL  == 'FTP' }}
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ vars.HOST }}
          username: ${{ vars.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          port:  ${{ vars.PORT }}
          local-dir: ${{ vars.LOCAL_PATH }}
          server-dir: ${{ vars.REMOTE_PATH }}
